{"name": "test_division_for_integers_within_borders[left_negative_operand]", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидается 0, получено -1\nassert -1 == 0\n  --1\n  +0", "trace": "setup = None, param_test = ({'left_operand': -2019208278, 'operation': '/', 'right_operand': 217907793}, 0)\n\n    @allure.suite(\"Тестирование калькулятора\")\n    @allure.feature(\"Тестирование функции калькулятора - деление\")\n    # @allure.title(\"Тест на проверку деления с числами внутри диапазона integer\")\n    def test_division_for_integers_within_borders(setup, param_test):\n        (input_data, expected_data) = param_test\n        with allure.step(f\"отправляем запрос с входными данными {input_data} и получаем результат расчёта\"):\n            result = do_request_and_get_response(input_data)\n        expected_result = expected_data\n        with allure.step(\"Проверяем, что полученный результат = ожидаемому\"):\n>           assert result == expected_result, f\"Ожидается {expected_result}, получено {result}\"\nE           AssertionError: Ожидается 0, получено -1\nE           assert -1 == 0\nE             --1\nE             +0\n\nexpected_data = 0\nexpected_result = 0\ninput_data = {'left_operand': -2019208278, 'operation': '/', 'right_operand': 217907793}\nparam_test = ({'left_operand': -2019208278, 'operation': '/', 'right_operand': 217907793}, 0)\nresult     = -1\nsetup      = None\n\ntests\\test_division.py:14: AssertionError"}, "steps": [{"name": "отправляем запрос с входными данными {'left_operand': -2019208278, 'operation': '/', 'right_operand': 217907793} и получаем результат расчёта", "status": "passed", "start": 1579357578634, "stop": 1579357578810}, {"name": "Проверяем, что полученный результат = ожидаемому", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидается 0, получено -1\nassert -1 == 0\n  --1\n  +0\n", "trace": "  File \"C:\\Users\\Leonid\\PycharmProjects\\ModulBank\\tests\\test_division.py\", line 14, in test_division_for_integers_within_borders\n    assert result == expected_result, f\"Ожидается {expected_result}, получено {result}\"\n"}, "start": 1579357578810, "stop": 1579357578811}], "parameters": [{"name": "param_test", "value": "({'left_operand': -2019208278, 'operation': '/', 'right_operand': 217907793}, 0)"}], "start": 1579357578634, "stop": 1579357578811, "uuid": "7e3984b3-eade-4f04-af8d-ec266b715776", "historyId": "92ecb419375620850a0fa5f9bde0ae9d", "testCaseId": "9f6ca8f533d02c3e239a5a6be76bb0f5", "fullName": "tests.test_division#test_division_for_integers_within_borders", "labels": [{"name": "feature", "value": "Тестирование функции калькулятора - деление"}, {"name": "suite", "value": "Тестирование калькулятора"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "DESKTOP-1R5TURF"}, {"name": "thread", "value": "4568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_division"}]}