{"name": "Тест на проверку деления с числами внутри диапазона integer", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидается 5, получено -1\nassert -1 == 5\n  --1\n  +5", "trace": "setup = None, param_test = ({'left_operand': -940269625, 'operation': '/', 'right_operand': -182831233}, 5.142828222353016)\n\n    @allure.suite(\"Тестирование калькулятора\")\n    @allure.feature(\"Тестирование функции калькулятора - деление\")\n    @allure.title(\"Тест на проверку деления с числами внутри диапазона integer\")\n    def test_division_for_integers_within_borders(setup, param_test):\n        (input_data, expected_data) = param_test\n        with allure.step(f\"отправляем запрос с входными данными {input_data} и получаем результат расчёта\"):\n            result = do_request_and_get_response(input_data)\n        expected_result = int(expected_data)\n        with allure.step(\"Проверяем, что полученный результат = ожидаемому\"):\n>           assert result == expected_result, f\"Ожидается {expected_result}, получено {result}\"\nE           AssertionError: Ожидается 5, получено -1\nE           assert -1 == 5\nE             --1\nE             +5\n\nexpected_data = 5.142828222353016\nexpected_result = 5\ninput_data = {'left_operand': -940269625, 'operation': '/', 'right_operand': -182831233}\nparam_test = ({'left_operand': -940269625, 'operation': '/', 'right_operand': -182831233}, 5.142828222353016)\nresult     = -1\nsetup      = None\n\ntests\\test_division.py:14: AssertionError"}, "steps": [{"name": "отправляем запрос с входными данными {'left_operand': -940269625, 'operation': '/', 'right_operand': -182831233} и получаем результат расчёта", "status": "passed", "start": 1579356705176, "stop": 1579356705363}, {"name": "Проверяем, что полученный результат = ожидаемому", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидается 5, получено -1\nassert -1 == 5\n  --1\n  +5\n", "trace": "  File \"C:\\Users\\Leonid\\PycharmProjects\\ModulBank\\tests\\test_division.py\", line 14, in test_division_for_integers_within_borders\n    assert result == expected_result, f\"Ожидается {expected_result}, получено {result}\"\n"}, "start": 1579356705363, "stop": 1579356705364}], "parameters": [{"name": "param_test", "value": "({'left_operand': -940269625, 'operation': '/', 'right_operand': -182831233}, 5.142828222353016)"}], "start": 1579356705175, "stop": 1579356705366, "uuid": "e7e46d1e-c79a-49b3-8375-389c1989c1dc", "historyId": "a455d1b77f32359f44fd79db59d7e22b", "testCaseId": "9f6ca8f533d02c3e239a5a6be76bb0f5", "fullName": "tests.test_division#test_division_for_integers_within_borders", "labels": [{"name": "suite", "value": "Тестирование калькулятора"}, {"name": "feature", "value": "Тестирование функции калькулятора - деление"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "DESKTOP-1R5TURF"}, {"name": "thread", "value": "2532-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_division"}]}