{"name": "Тест на проверку деления с числами внутри диапазона integer", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидается 7, получено -1\nassert -1 == 7\n  --1\n  +7", "trace": "setup = None, param_test = ({'left_operand': -1167911127, 'operation': '/', 'right_operand': -166487298}, 7.015016406837235)\n\n    @allure.feature(\"Тестирование функции калькулятора - деление\")\n    @allure.title(\"Тест на проверку деления с числами внутри диапазона integer\")\n    def test_division_for_integers_within_borders(setup, param_test):\n        (input_data, expected_data) = param_test\n        with allure.step(f\"отправляем запрос с входными данными {input_data} и получаем результат расчёта\"):\n            result = do_request_and_get_response(input_data)\n        expected_result = int(expected_data)\n        with allure.step(\"Проверяем, что полученный результат = ожидаемому\"):\n>           assert result == expected_result, f\"Ожидается {expected_result}, получено {result}\"\nE           AssertionError: Ожидается 7, получено -1\nE           assert -1 == 7\nE             --1\nE             +7\n\nexpected_data = 7.015016406837235\nexpected_result = 7\ninput_data = {'left_operand': -1167911127, 'operation': '/', 'right_operand': -166487298}\nparam_test = ({'left_operand': -1167911127, 'operation': '/', 'right_operand': -166487298}, 7.015016406837235)\nresult     = -1\nsetup      = None\n\ntests\\test_division.py:13: AssertionError"}, "steps": [{"name": "отправляем запрос с входными данными {'left_operand': -1167911127, 'operation': '/', 'right_operand': -166487298} и получаем результат расчёта", "status": "passed", "start": 1579356539163, "stop": 1579356539347}, {"name": "Проверяем, что полученный результат = ожидаемому", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидается 7, получено -1\nassert -1 == 7\n  --1\n  +7\n", "trace": "  File \"C:\\Users\\Leonid\\PycharmProjects\\ModulBank\\tests\\test_division.py\", line 13, in test_division_for_integers_within_borders\n    assert result == expected_result, f\"Ожидается {expected_result}, получено {result}\"\n"}, "start": 1579356539347, "stop": 1579356539348}], "parameters": [{"name": "param_test", "value": "({'left_operand': -1167911127, 'operation': '/', 'right_operand': -166487298}, 7.015016406837235)"}], "start": 1579356539163, "stop": 1579356539350, "uuid": "cb93e1e6-fa29-4ce6-9067-5c1fad5c7bce", "historyId": "a455d1b77f32359f44fd79db59d7e22b", "testCaseId": "9f6ca8f533d02c3e239a5a6be76bb0f5", "fullName": "tests.test_division#test_division_for_integers_within_borders", "labels": [{"name": "feature", "value": "Тестирование функции калькулятора - деление"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_division"}, {"name": "host", "value": "DESKTOP-1R5TURF"}, {"name": "thread", "value": "3512-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_division"}]}